---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
  category: "categories"
baseurl: "http://felipemaldonado.github.io/blog"
title: "First attempt of website"
canonifyurls: true 
...